name: Setup

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Setup Android SDK
          uses: android-actions/setup-android@v3